import Image from 'next/image'
import { ArrowDown, ArrowLeft, CakeSlice, CalendarCheck, Check, MessageCircle, Moon, Sparkles, Trees, UtensilsCrossed, UsersRound } from 'lucide-react'
import ServicePageHeader from '@/components/ServicePageHeader'
import SocialBar from '@/components/SocialBar'
import Footer from '@/components/Footer'
import { Reveal, FloatOnView } from '@/components/Reveal'
import { Flourish } from '@/components/Ornaments'
import { contact } from '@/lib/contact'
import GardenEventsCarousel from './GardenEventsCarousel'

const image = (name: string, ext = 'png') => `/images/New folder/${name}.${ext}`

const features = [
  { icon: Trees, title: 'مساحة خضراء واسعة', text: 'أشجار وعشب طبيعي يمنحان المكان راحة وهدوءاً من أول لحظة.' },
  { icon: Sparkles, title: 'تفاصيل مائية', text: 'نافورة وسط الخضرة تضيف صوتاً وحركة لطيفة إلى الجلسة.' },
  { icon: Moon, title: 'أجواء مسائية', text: 'إضاءة دافئة تمتد بين الأشجار وتحول المساء إلى مشهد ساحر.' },
  { icon: UsersRound, title: 'جلسات لكل لمة', text: 'توزيع مريح للطاولات يناسب العائلة والأصدقاء والزيارات الهادئة.' },
]

export default function GardenLoungePage() {
  return (
    <main className="site-shell" dir="rtl">
      <ServicePageHeader /><SocialBar />

      <section className="relative isolate min-h-[92svh] overflow-hidden bg-[#0b3329] pt-[104px] text-[#fbf8f3] lg:min-h-screen lg:pt-[122px]">
        <div className="absolute inset-0"><Image src={image('48')} alt="منتزه لمة خير عند الغروب" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,40,31,.7),rgba(8,40,31,.16),rgba(8,40,31,.62))]" /><div className="absolute inset-x-0 bottom-0 h-52 bg-gradient-to-t from-[#f8f4ef] via-[#f8f4ef]/22 to-transparent" /></div>
        <FloatOnView className="pointer-events-none absolute right-[5%] top-[24%] block h-[110px] w-[110px] opacity-[0.13] invert sm:h-[170px] sm:w-[170px] lg:h-[46vh] lg:w-[18vw]"><img src="/ornaments/floral-light.svg" alt="" aria-hidden="true" className="h-full w-full object-contain" /></FloatOnView>
        <div className="section-frame section-pad relative z-10 flex min-h-[calc(92svh-104px)] flex-col items-center justify-center text-center lg:min-h-[calc(100svh-122px)]">
          <Reveal direction="scale" className="mx-auto flex h-[86px] w-[86px] items-center justify-center rounded-full border border-[#d7b672]/45 bg-[#fbf8f3]/10 text-[#d7b672] shadow-[0_20px_60px_rgba(0,0,0,.25)] backdrop-blur-md lg:h-[106px] lg:w-[106px]"><Trees className="h-12 w-12 stroke-[1.35] lg:h-16 lg:w-16" /></Reveal>
          <Reveal direction="down" delay={0.08} className="flex flex-col items-center"><p className="mt-7 w-fit rounded-full border border-[#f1cf80]/50 bg-[#08281f]/70 px-5 py-2 text-[16px] font-extrabold text-[#f6d98e] shadow-[0_5px_20px_rgba(0,0,0,.4)] backdrop-blur-md lg:text-[19px]">المنتزه والجلسات</p><h1 className="heading-font mt-3 max-w-[880px] text-[clamp(3rem,6.8vw,8.7rem)] font-semibold leading-[1.05] tracking-[-0.06em] text-white">مساحات هادئة للتواصل الجميل</h1></Reveal>
          <Reveal direction="up" delay={0.18}><p className="mx-auto mt-6 max-w-[720px] text-[16px] font-medium leading-[2] text-[#fbf8f3]/88 lg:text-[20px]">جلسات خارجية تنبض بالخضرة، صوت الماء، وضوء المساء الدافئ لتكون كل لمة أخف وأجمل.</p></Reveal>
          <Reveal direction="up" delay={0.3}><a href="#park-beauty" className="mt-10 inline-flex items-center gap-3 rounded-full border border-[#f1cf80]/65 bg-[#08281f]/65 px-5 py-3 text-[13px] font-extrabold text-[#f6d98e] shadow-[0_8px_28px_rgba(0,0,0,.32)] backdrop-blur-md transition hover:bg-[#08281f]/85 lg:text-[15px]"><ArrowDown className="h-4 w-4 animate-bounce" />استكشف تفاصيل المنتزه</a></Reveal>
        </div>
      </section>

      <section id="park-beauty" className="flex min-h-screen items-center overflow-hidden bg-[#f8f4ef] py-16 lg:py-20"><div className="section-frame section-pad grid items-center gap-10 lg:grid-cols-[.78fr_1.22fr] lg:gap-[5vw]">
        <Reveal direction="right" className="text-center lg:text-right"><p className="text-[15px] font-extrabold text-[#a97734]">جمال المكان</p><h2 className="heading-font mt-3 text-[clamp(2.7rem,4.6vw,5.6rem)] font-semibold leading-[1.08] text-[#0b3329]">حديقة تتبدّل ملامحها مع الضوء</h2><Flourish className="mx-auto mt-5 h-7 w-48 text-[#b98a43] lg:mx-0" /><p className="mt-6 text-[16px] font-medium leading-[2.1] text-[#67716b] lg:text-[18px]">هادئة ومشرقة في النهار، ذهبية عند الغروب، ومليئة بالدفء مساءً. تتكامل الخضرة مع صوت النافورة والجلسات الموزعة براحة، لتبدو المساحة كلها كتجربة واحدة لا كمشاهد منفصلة.</p><div className="mt-7 flex flex-wrap justify-center gap-2 lg:justify-start">{['خضرة واسعة','نافورة هادئة','إضاءة دافئة'].map((item) => <span key={item} className="rounded-full border border-[#d8cab4] bg-white/70 px-4 py-2 text-[13px] font-bold text-[#0b3329]">{item}</span>)}</div></Reveal>
        <div className="grid h-[62svh] min-h-[500px] grid-cols-[1.35fr_.65fr] grid-rows-2 gap-3 lg:h-[78svh] lg:max-h-[760px]">
          <Reveal direction="left" className="relative row-span-2 overflow-hidden rounded-[30px]"><Image src={image('50')} alt="المنتزه في وضح النهار" fill sizes="(min-width:1024px) 48vw,70vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#08281f]/55 via-transparent to-transparent" /><p className="absolute bottom-6 right-6 text-[18px] font-extrabold text-white">خضرة ومساحة تفتح النفس</p></Reveal>
          <Reveal direction="down" className="relative overflow-hidden rounded-[26px]"><Image src={image('51')} alt="نافورة المنتزه والخضرة" fill sizes="(min-width:1024px) 24vw,30vw" className="object-cover" /></Reveal>
          <Reveal direction="up" className="relative overflow-hidden rounded-[26px]"><Image src={image('47')} alt="النافورة عند الغروب" fill sizes="(min-width:1024px) 24vw,30vw" className="object-cover" /></Reveal>
        </div>
      </div></section>

      <section className="overflow-hidden bg-[#fbf8f3] py-20 lg:py-28"><div className="section-frame section-pad grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr] lg:gap-[6vw]">
        <Reveal direction="right"><p className="text-[15px] font-extrabold text-[#b98a43]">من أول خطوة</p><h2 className="heading-font mt-3 text-[clamp(2.8rem,4.8vw,5.7rem)] font-semibold leading-[1.05] text-[#0b3329]">تفاصيل ترحّب فيكم قبل الجلسة</h2><p className="mt-6 text-[16px] font-medium leading-[2.1] text-[#66716b]">من مدخل لمة خير إلى الممر المضاء، تبدأ التجربة بهدوء بصري وخضرة وإضاءة مدروسة تقودكم نحو الحديقة.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['مدخل واضح ومرتب','ممر بإضاءة دافئة','خضرة ممتدة','زوايا جميلة للتصوير'].map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl bg-[#f1eadf] px-4 py-3 text-[14px] font-bold text-[#0b3329]"><Check className="h-4 w-4 shrink-0 text-[#b98a43]" />{item}</div>)}</div></Reveal>
        <div className="grid grid-cols-2 gap-4">{[['1','jpg'],['44','png']].map(([name, ext], index) => <Reveal key={name} direction="up" delay={index * .08}><div className="relative aspect-[4/5] overflow-hidden rounded-[26px] shadow-[0_18px_45px_rgba(11,51,41,.12)]"><Image src={image(name, ext)} alt={index === 0 ? 'مدخل لمة خير' : 'الممر المضاء المؤدي إلى المنتزه'} fill sizes="(min-width:1024px) 24vw,50vw" className="object-cover" /></div></Reveal>)}</div>
      </div></section>

      <section id="park-moments" className="scroll-mt-28 bg-[#0a3027] py-20 text-white lg:py-28"><div className="section-frame section-pad">
        <Reveal direction="down" className="mx-auto max-w-[790px] text-center"><p className="text-[15px] font-extrabold text-[#d7b672]">من العصر إلى آخر السهرة</p><h2 className="heading-font mt-3 text-[clamp(2.8rem,5vw,6rem)] font-semibold leading-[1.05]">كل وقت له أجواؤه</h2></Reveal>
        <div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[['2','jpg','هدوء الماء'],['3','jpg','جلسات تحت الأشجار'],['4','jpg','النافورة والجلسات'],['49','png','دفء المساء']].map(([name, ext, label], index) => <Reveal key={name} direction="up" delay={index * .06}><figure className="group relative aspect-[4/5] overflow-hidden rounded-[28px] bg-black/20"><Image src={image(name, ext)} alt={label} fill sizes="(min-width:1024px) 24vw,(min-width:768px) 50vw,100vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-transparent" /><figcaption className="absolute bottom-0 p-5 text-[17px] font-extrabold">{label}</figcaption></figure></Reveal>)}</div>
      </div></section>

      <section className="bg-[#f8f4ef] py-20 lg:py-28"><div className="section-frame section-pad">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({ icon: Icon, title, text }, index) => <Reveal key={title} direction="up" delay={index * .07}><article className="h-full rounded-[28px] border border-[#dacbad] bg-white/70 p-7 text-center shadow-[0_16px_45px_rgba(11,51,41,.06)]"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#0b3329] text-[#d7b672]"><Icon className="h-7 w-7 stroke-[1.4]" /></div><h3 className="mt-5 text-[18px] font-extrabold text-[#0b3329]">{title}</h3><p className="mt-3 text-[14px] font-medium leading-[1.9] text-[#6b7069]">{text}</p></article></Reveal>)}</div>
        <div className="mt-16 grid grid-cols-2 gap-4 lg:grid-cols-3">{[['63','المشهد الكامل ليلاً'],['64','جلسات موزعة براحة'],['65','زوايا حميمة تحت الشجر']].map(([name, label], index) => <Reveal key={name} direction="up" delay={index * .07} className={index === 2 ? 'col-span-2 lg:col-span-1' : ''}><figure className={`relative overflow-hidden rounded-[30px] shadow-[0_22px_60px_rgba(11,51,41,.16)] ${index === 2 ? 'aspect-[2/1] md:aspect-[2.2/1] lg:aspect-[4/3]' : 'aspect-[4/3]'}`}><Image src={image(name)} alt={label} fill sizes="(min-width:1024px) 33vw,100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent" /><figcaption className="absolute bottom-5 right-5 text-[17px] font-extrabold text-white">{label}</figcaption></figure></Reveal>)}</div>
      </div></section>

      <section id="private-events" className="relative scroll-mt-28 overflow-hidden bg-[#071f19] py-20 text-white lg:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_12%_18%,rgba(215,182,114,.18),transparent_28rem)]" /><div className="section-frame section-pad relative z-10">
        <Reveal direction="down" className="mx-auto max-w-[900px] text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-[#d7b672]/45 bg-white/5 text-[#d7b672]"><CalendarCheck className="h-8 w-8 stroke-[1.4]" /></div><p className="mt-5 text-[15px] font-extrabold text-[#d7b672]">احجز المنتزه لمناسبتك الخاصة</p><h2 className="heading-font mt-3 text-[clamp(2.8rem,5.2vw,6.4rem)] font-semibold leading-[1.05]">مكان واحد… وذكريات على قدّ فرحتكم</h2><p className="mx-auto mt-6 max-w-[740px] text-[16px] font-medium leading-[2] text-white/72">من عيد ميلاد عائلي إلى عرس أو سهرة خاصة، يمكن حجز المنتزه وتحويل مساحته إلى أجواء تناسب مناسبتكم.</p></Reveal>
        <GardenEventsCarousel />
      </div></section>

      <section id="garden-dining" className="relative scroll-mt-28 overflow-hidden bg-[#f8f4ef] py-20 lg:py-28"><div className="section-frame section-pad">
        <Reveal direction="down" className="mx-auto max-w-[780px] text-center"><p className="text-[14px] font-extrabold text-[#a97734]">كمّلوا لمّتكم بطلبكم المفضل</p><h2 className="heading-font mt-2 text-[clamp(2.5rem,4.5vw,5.2rem)] font-semibold leading-[1.1] text-[#0b3329]">من مطابخ لمة خير إلى جلستكم</h2><p className="mx-auto mt-5 max-w-[680px] text-[15px] font-medium leading-[2] text-[#66716b] lg:text-[17px]">خلال جلستكم في المنتزه، يمكنكم الطلب من المطبخ الشرقي أو اختيار الحلويات الطازجة لتكتمل الضيافة على ذوقكم.</p></Reveal>
        <div className="mx-auto mt-12 grid max-w-[1220px] gap-5 lg:grid-cols-2">
          <Reveal direction="right"><article className="group relative min-h-[430px] overflow-hidden rounded-[32px] bg-[#0b3329] shadow-[0_25px_65px_rgba(11,51,41,.16)]"><Image src="/images/lammat-khair/home/service-eastern-kitchen.jpg" alt="أطباق المطبخ الشرقي" fill sizes="(min-width:1024px) 50vw,100vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#061e18] via-[#061e18]/25 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7 text-white lg:p-9"><UtensilsCrossed className="h-8 w-8 text-[#e4c88f]" /><h3 className="heading-font mt-3 text-[36px] font-semibold">المطبخ الشرقي</h3><p className="mt-2 max-w-[480px] text-[14px] font-medium leading-[1.9] text-white/78">أطباق شرقية، مشاوي ووجبات كاملة جاهزة لترافق جلستكم.</p><a href="/eastern-kitchen" className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#d7b672] px-6 py-3 text-[13px] font-extrabold text-[#0b3329] transition hover:bg-[#e5c98e]">تعرّفوا على المطبخ <ArrowLeft className="h-4 w-4" /></a></div></article></Reveal>
          <Reveal direction="left"><article className="group relative min-h-[430px] overflow-hidden rounded-[32px] bg-[#0b3329] shadow-[0_25px_65px_rgba(11,51,41,.16)]"><Image src="/images/lammat-khair/home/service-bakery-sweets.jpg" alt="حلويات لمة خير" fill sizes="(min-width:1024px) 50vw,100vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#061e18] via-[#061e18]/25 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7 text-white lg:p-9"><CakeSlice className="h-8 w-8 text-[#e4c88f]" /><h3 className="heading-font mt-3 text-[36px] font-semibold">المخبز والحلويات</h3><p className="mt-2 max-w-[480px] text-[14px] font-medium leading-[1.9] text-white/78">حلويات ومخبوزات طازجة تضيف للّمة ضيافة حلوة ومميزة.</p><a href="/bakery" className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#d7b672] px-6 py-3 text-[13px] font-extrabold text-[#0b3329] transition hover:bg-[#e5c98e]">تعرّفوا على الحلويات <ArrowLeft className="h-4 w-4" /></a></div></article></Reveal>
        </div>
      </div></section>

      <section className="relative isolate overflow-hidden bg-[#f8f4ef] py-16 lg:py-22"><div className="section-frame section-pad"><Reveal direction="up" once className="relative mx-auto max-w-[1380px] overflow-hidden rounded-[34px] bg-[#0b3329] px-6 py-12 text-center text-[#fbf8f3] shadow-[0_34px_76px_rgba(12,50,41,.18)] lg:px-20 lg:py-14"><div className="absolute inset-0 dark-luxury-surface opacity-95" /><div className="relative z-10 mx-auto max-w-[780px]"><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-full border border-[#d7b672]/35 text-[#d7b672]"><Trees className="h-9 w-9 stroke-[1.4]" /></div><p className="text-[14px] font-extrabold text-[#d7b672]">لترتيب مناسبتكم</p><h2 className="heading-font mt-2 text-[clamp(2.3rem,4vw,4.8rem)] font-semibold text-[#fbf8f3]">خلّونا نجهّز التفاصيل معكم</h2><p className="mx-auto mt-5 max-w-[680px] text-[15px] font-medium leading-[2] text-[#fbf8f3]/78 lg:text-[17px]">أرسلوا لنا التاريخ، نوع المناسبة، وعدد الضيوف لنساعدكم في اختيار الترتيب الأنسب للمكان.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href={contact.whatsapp} target="_blank" rel="noreferrer" className="btn-gold min-w-[200px] gap-2"><MessageCircle className="h-4 w-4" />تواصل عبر واتساب</a><a href={contact.phoneHref} className="inline-flex min-h-[42px] min-w-[200px] items-center justify-center gap-2 border border-white/45 px-7 text-[14px] font-extrabold text-white transition hover:bg-white/10"><span>اتصل بنا</span><bdi dir="ltr">{contact.phoneDisplay}</bdi></a></div></div></Reveal></div></section>

      <Footer />
    </main>
  )
}
