export const siteImages = {
  logo: '/images/logo-lammat-khair.png',
  hero: '/images/New folder/43.png',
  garden: '/images/lammat-khair/home/about-image-2.jpg',
  dining: '/images/lammat-khair/home/service-bakery-image-5.jpg',
  bakeryHero: '/images/New folder/32.jpg',
  bakeryCakes: '/images/New folder/18.jpg',
  bakeryArabic: '/images/New folder/5.jpg',
  bakeryNests: '/images/New folder/26.jpg',
  bakeryPistachio: '/images/New folder/35.jpg',
  bakeryNuts: '/images/New folder/36.jpg',
  food: '/images/lammat-khair/home/service-eastern-kitchen-image-15.jpg',
  easternHero: '/images/New folder/12.jpg',
  easternPastries: '/images/New folder/6.jpg',
  easternRice: '/images/New folder/7.jpg',
  easternMain: '/images/New folder/8.jpg',
  easternMezze: '/images/New folder/9.jpg',
  easternGrill: '/images/New folder/10.jpg',
  easternRiceTray: '/images/New folder/11.jpg',
  easternKibbeh: '/images/New folder/13.jpg',
  easternCrispy: '/images/New folder/14.jpg',
  easternKubbeh: '/images/New folder/15.jpg',
  easternWings: '/images/New folder/16.jpg',
  easternMandiPlate: '/images/New folder/17.jpg',
  mandiFamilyTray: '/images/New folder/11.jpg',
  mandiSinglePlate: '/images/New folder/24.jpg',
  mandiMajlisDay: '/images/New folder/59.png',
  mandiMajlisEvening: '/images/New folder/60.png',
  mandiMajlisTable: '/images/New folder/61.png',
  mandiMajlisFeast: '/images/New folder/62.png',
  easternMixedGrill: '/images/lammat-khair/home/gallery-main-grill.jpg',
  easternTabbouleh: '/images/lammat-khair/home/gallery-tabbouleh.jpg',
  easternYalanji: '/images/lammat-khair/home/gallery-yalanji.jpg',
  salad1: '/images/New folder/salad1.png',
  salad2: '/images/New folder/salad2.png',
  salad3: '/images/New folder/salad3.jpg',
  salad4: '/images/New folder/salad4.png',
  sandwich1: '/images/New folder/sandwich1.png',
  sandwich2: '/images/New folder/sandwich2.png',
  sandwich3: '/images/New folder/sandwich3.png',
  sandwich4: '/images/New folder/sandwich4.png',
  mandi: '/images/lammat-khair/home/service-yemeni-mandi.jpg',
  park: '/images/lammat-khair/home/service-garden-image-4.jpg',
  hall: '/images/lammat-khair/home/service-event-hall-image-38.png',
  hallHero: '/images/New folder/52.png',
  hallWide: '/images/New folder/53.png',
  hallInterior: '/images/New folder/38.png',
  hallChandelier: '/images/New folder/55.png',
  hallSeatingFront: '/images/New folder/56.png',
  hallSeatingSide: '/images/New folder/57.png',
  hallSeatingPerspective: '/images/New folder/58.png',
  hallOverview: '/images/New folder/37.png',
  galleryHall: '/images/New folder/47.png',
  galleryDesserts: '/images/New folder/38.png',
  galleryGardenNight: '/images/New folder/18.jpg',
  galleryFoodTable: '/images/New folder/10.jpg',
  galleryOutdoor: '/images/New folder/48.png',
  parkHero: '/images/New folder/63.png',
  parkWide: '/images/New folder/64.png',
  parkIntimate: '/images/New folder/65.png',
  parkEventDabke1: '/images/New folder/66.png',
  parkEventDabke2: '/images/New folder/67.png',
  parkEventFireworks: '/images/New folder/68.png',
  parkEventSinger: '/images/New folder/69.png',
  parkEventFlares1: '/images/New folder/70.png',
  parkEventFlares2: '/images/New folder/71.png',
  parkBirthday: '/images/New folder/72.png',
}

export const localImageGuide = [
  {
    file: 'logo-lammat-khair.png',
    usage: 'شعار الموقع داخل الهيدر والفوتر',
    section: 'Header / Footer',
  },
  {
    file: 'hero-pavilion.jpg',
    usage: 'الصورة الكبيرة في أول الموقع',
    section: 'HeroSection',
  },
  {
    file: 'garden-lounge.jpg',
    usage: 'صورة قسم عن لمة خير',
    section: 'AboutSection',
  },
  {
    file: 'event-hall.jpg',
    usage: 'كرت صالة المناسبات',
    section: 'ServicesSection',
  },
  {
    file: 'desserts.jpg',
    usage: 'كرت الفرن والحلويات وصورة من المعرض',
    section: 'ServicesSection / GallerySection',
  },
  {
    file: 'eastern-kitchen.jpg',
    usage: 'كرت المطبخ الشرقي',
    section: 'ServicesSection',
  },
  {
    file: 'yemeni-mandi.jpg',
    usage: 'كرت المندي اليمني',
    section: 'ServicesSection',
  },
  {
    file: 'park-sessions.jpg',
    usage: 'كرت المنتزه والجلسات',
    section: 'ServicesSection',
  },
  {
    file: 'gallery-hall.jpg',
    usage: 'الصورة الأولى في معرض الصور',
    section: 'GallerySection',
  },
  {
    file: 'gallery-desserts.jpg',
    usage: 'الصورة الثانية في معرض الصور',
    section: 'GallerySection',
  },
  {
    file: 'gallery-garden-night.jpg',
    usage: 'الصورة الثالثة في معرض الصور',
    section: 'GallerySection',
  },
  {
    file: 'gallery-food-table.jpg',
    usage: 'الصورة الرابعة في معرض الصور',
    section: 'GallerySection',
  },
  {
    file: 'gallery-outdoor.jpg',
    usage: 'الصورة الخامسة في معرض الصور',
    section: 'GallerySection',
  },
]

export const colors = {
  cream: '#f8f4ef',
  creamWarm: '#f3eee6',
  green: '#0b3329',
  green2: '#123f35',
  gold: '#b98a43',
  ink: '#113d35',
}
